-- ====================================================================
-- CampusBite - Supabase PostgreSQL Schema (MVP Phase)
-- ====================================================================
-- Run this script in your Supabase Dashboard:
-- 1. Go to your Supabase project -> SQL Editor
-- 2. Click "New query"
-- 3. Paste this entire script and click "Run"
-- ====================================================================

-- 1. CANTEENS TABLE
CREATE TABLE IF NOT EXISTS public.canteens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    is_open BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. MENU ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canteen_id BIGINT NOT NULL REFERENCES public.canteens(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canteen_id BIGINT REFERENCES public.canteens(id) ON DELETE SET NULL,
    user_id TEXT, -- Nullable in this phase (no auth)
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. ORDER ITEMS TABLE (Purchased items snapshot)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    menu_item_id BIGINT REFERENCES public.menu_items(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    quantity INT NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL
);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) FOR MVP PHASE
-- Since authentication is disabled in this phase, allow open access
-- so the backend can read and write using Supabase API keys.
-- ====================================================================

ALTER TABLE public.canteens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Create open policies for all CRUD operations
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public access on canteens') THEN
        CREATE POLICY "Allow public access on canteens" ON public.canteens FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public access on menu_items') THEN
        CREATE POLICY "Allow public access on menu_items" ON public.menu_items FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public access on orders') THEN
        CREATE POLICY "Allow public access on orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public access on order_items') THEN
        CREATE POLICY "Allow public access on order_items" ON public.order_items FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- ====================================================================
-- INITIAL SAMPLE DATA (Optional Seed)
-- ====================================================================
INSERT INTO public.canteens (name, location, is_open) 
VALUES
    ('Main Campus Canteen', 'Student Center, Ground Floor', true),
    ('North Block Food Corner', 'North Academic Block, 1st Floor', true)
ON CONFLICT DO NOTHING;

INSERT INTO public.menu_items (canteen_id, name, description, price, available)
VALUES
    (1, 'Veg Burger', 'Crispy vegetable patty with lettuce and cheese', 60.00, true),
    (1, 'Paneer Roll', 'Spiced cottage cheese wrapped in a paratha', 80.00, true),
    (1, 'Cold Coffee', 'Chilled blended coffee with chocolate syrup', 50.00, true),
    (1, 'Masala Dosa', 'Crispy crepe served with sambar and coconut chutney', 55.00, false),
    (2, 'Hot Chocolate', 'Rich hot cocoa with steamed milk', 45.00, true)
ON CONFLICT DO NOTHING;
