/**
 * GD Palate – Menu Data
 * Source: Approximation based on campus canteen categories.
 * Replace with real backend data when API integration is ready.
 */

const MENU_CATEGORIES = [
  { id: "all",          label: "All" },
  { id: "breakfast",    label: "Breakfast" },
  { id: "dosa",         label: "Dosa" },
  { id: "chinese",      label: "Chinese" },
  { id: "meals",        label: "Meals" },
  { id: "south-indian", label: "South Indian" },
  { id: "egg",          label: "Egg" },
  { id: "biryani",      label: "Biryani" },
  { id: "bakery",       label: "Bakery" },
  { id: "beverages",    label: "Beverages" },
  { id: "fresh-juice",  label: "Fresh Juice" },
  { id: "sandwich",     label: "Sandwich & Rolls" },
  { id: "pav-bhaji",    label: "Pav Bhaji" },
  { id: "ice-cream",    label: "Ice Cream" },
  { id: "water",        label: "Water Bottle" },
  { id: "added",        label: "Added Items" },
];

/** @type {MenuItem[]} */
const MENU_ITEMS = [
  // ─── BREAKFAST ────────────────────────────────────────────────────────────
  {
    id: "b001",
    name: "Idli (2 pcs)",
    description: "Soft steamed rice cakes served with sambar and coconut chutney",
    price: 25,
    category: "breakfast",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "",
  },
  {
    id: "b002",
    name: "Vada (2 pcs)",
    description: "Crispy lentil fritters with sambar and chutney",
    price: 30,
    category: "breakfast",
    isVeg: true,
    available: true,
    emoji: "🍩",
    imageUrl: "",
  },
  {
    id: "b003",
    name: "Idli Vada Combo",
    description: "2 idlis + 1 vada with sambar and chutneys",
    price: 45,
    category: "breakfast",
    isVeg: true,
    available: true,
    emoji: "🍱",
    imageUrl: "",
  },
  {
    id: "b004",
    name: "Pongal",
    description: "Savoury rice and lentil porridge with ghee and pepper",
    price: 35,
    category: "breakfast",
    isVeg: true,
    available: true,
    emoji: "🥣",
    imageUrl: "",
  },
  {
    id: "b005",
    name: "Upma",
    description: "Semolina cooked with vegetables and tempered spices",
    price: 30,
    category: "breakfast",
    isVeg: true,
    available: false,
    emoji: "🥣",
    imageUrl: "",
  },

  // ─── DOSA ─────────────────────────────────────────────────────────────────
  {
    id: "d001",
    name: "Plain Dosa",
    description: "Crispy thin rice crepe with sambar and coconut chutney",
    price: 35,
    category: "dosa",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "d002",
    name: "Masala Dosa",
    description: "Crispy dosa stuffed with spiced potato filling",
    price: 50,
    category: "dosa",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "d003",
    name: "Ghee Roast Dosa",
    description: "Dosa roasted in generous ghee until golden and crunchy",
    price: 60,
    category: "dosa",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "d004",
    name: "Rava Dosa",
    description: "Crispy semolina crepe with onion and green chilli",
    price: 55,
    category: "dosa",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "",
  },
  {
    id: "d005",
    name: "Egg Dosa",
    description: "Dosa topped with a fried egg and masala",
    price: 65,
    category: "dosa",
    isVeg: false,
    available: true,
    emoji: "🍳",
    imageUrl: "",
  },
  {
    id: "d006",
    name: "Onion Dosa",
    description: "Dosa topped with caramelised onions and chilli",
    price: 45,
    category: "dosa",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "",
  },

  // ─── CHINESE ──────────────────────────────────────────────────────────────
  {
    id: "c001",
    name: "Veg Fried Rice",
    description: "Wok-tossed rice with mixed vegetables and soy sauce",
    price: 70,
    category: "chinese",
    isVeg: true,
    available: true,
    emoji: "🍚",
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c002",
    name: "Egg Fried Rice",
    description: "Fried rice tossed with scrambled eggs",
    price: 80,
    category: "chinese",
    isVeg: false,
    available: true,
    emoji: "🍚",
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c003",
    name: "Chicken Fried Rice",
    description: "Wok rice with tender chicken pieces and soy glaze",
    price: 100,
    category: "chinese",
    isVeg: false,
    available: true,
    emoji: "🍚",
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c004",
    name: "Veg Noodles",
    description: "Hakka noodles with crunchy vegetables and sauces",
    price: 70,
    category: "chinese",
    isVeg: true,
    available: true,
    emoji: "🍜",
    imageUrl: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c005",
    name: "Egg Noodles",
    description: "Hakka noodles stir-fried with eggs",
    price: 80,
    category: "chinese",
    isVeg: false,
    available: true,
    emoji: "🍜",
    imageUrl: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c006",
    name: "Chicken Noodles",
    description: "Hakka noodles with juicy chicken and Asian sauces",
    price: 100,
    category: "chinese",
    isVeg: false,
    available: true,
    emoji: "🍜",
    imageUrl: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c007",
    name: "Gobi Manchurian",
    description: "Crispy cauliflower in spicy Manchurian sauce",
    price: 80,
    category: "chinese",
    isVeg: true,
    available: false,
    emoji: "🥦",
    imageUrl: "",
  },

  // ─── MEALS ────────────────────────────────────────────────────────────────
  {
    id: "m001",
    name: "Veg Meals",
    description: "Rice, sambar, rasam, 2 curries, papad, pickle and dessert",
    price: 80,
    category: "meals",
    isVeg: true,
    available: true,
    emoji: "🍛",
    imageUrl: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "m002",
    name: "Non-Veg Meals",
    description: "Rice, sambar, rasam, chicken curry, papad, pickle and dessert",
    price: 110,
    category: "meals",
    isVeg: false,
    available: true,
    emoji: "🍛",
    imageUrl: "",
  },
  {
    id: "m003",
    name: "Special Meals",
    description: "Full veg meals with extra curries, ghee rice and sweet",
    price: 100,
    category: "meals",
    isVeg: true,
    available: false,
    emoji: "🍛",
    imageUrl: "",
  },

  // ─── SOUTH INDIAN ─────────────────────────────────────────────────────────
  {
    id: "si001",
    name: "Sambar Rice",
    description: "Steamed rice mixed with lentil sambar",
    price: 40,
    category: "south-indian",
    isVeg: true,
    available: true,
    emoji: "🍲",
    imageUrl: "",
  },
  {
    id: "si002",
    name: "Curd Rice",
    description: "Soft rice tempered with mustard, curry leaves and yoghurt",
    price: 35,
    category: "south-indian",
    isVeg: true,
    available: true,
    emoji: "🍚",
    imageUrl: "",
  },
  {
    id: "si003",
    name: "Lemon Rice",
    description: "Tangy rice with turmeric, peanuts and lemon tempering",
    price: 40,
    category: "south-indian",
    isVeg: true,
    available: true,
    emoji: "🍋",
    imageUrl: "",
  },
  {
    id: "si004",
    name: "Tomato Rice",
    description: "Spiced rice cooked with fresh tomatoes and aromatics",
    price: 40,
    category: "south-indian",
    isVeg: true,
    available: false,
    emoji: "🍅",
    imageUrl: "",
  },
  {
    id: "si005",
    name: "Chapati (3 pcs)",
    description: "Soft whole-wheat flatbreads served with curry",
    price: 30,
    category: "south-indian",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "",
  },
  {
    id: "si006",
    name: "Poori (2 pcs)",
    description: "Puffed deep-fried bread with potato masala",
    price: 35,
    category: "south-indian",
    isVeg: true,
    available: true,
    emoji: "🫓",
    imageUrl: "",
  },

  // ─── EGG ──────────────────────────────────────────────────────────────────
  {
    id: "e001",
    name: "Boiled Eggs (2 pcs)",
    description: "Hard-boiled eggs with salt and pepper",
    price: 20,
    category: "egg",
    isVeg: false,
    available: true,
    emoji: "🥚",
    imageUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "e002",
    name: "Egg Bhurji",
    description: "Scrambled eggs with onion, tomato and spices",
    price: 40,
    category: "egg",
    isVeg: false,
    available: true,
    emoji: "🍳",
    imageUrl: "",
  },
  {
    id: "e003",
    name: "Omelette",
    description: "Fluffy 2-egg omelette with onion and green chilli",
    price: 35,
    category: "egg",
    isVeg: false,
    available: true,
    emoji: "🍳",
    imageUrl: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "e004",
    name: "Egg Curry",
    description: "Hard-boiled eggs simmered in spiced onion-tomato gravy",
    price: 55,
    category: "egg",
    isVeg: false,
    available: true,
    emoji: "🥘",
    imageUrl: "",
  },

  // ─── BIRYANI ──────────────────────────────────────────────────────────────
  {
    id: "br001",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice with spiced chicken and fried onions",
    price: 120,
    category: "biryani",
    isVeg: false,
    available: true,
    emoji: "🍗",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "br002",
    name: "Egg Biryani",
    description: "Aromatic biryani with boiled eggs and saffron",
    price: 90,
    category: "biryani",
    isVeg: false,
    available: true,
    emoji: "🥚",
    imageUrl: "",
  },
  {
    id: "br003",
    name: "Mushroom Biryani",
    description: "Basmati rice layered with spiced mushrooms and herbs",
    price: 90,
    category: "biryani",
    isVeg: true,
    available: true,
    emoji: "🍄",
    imageUrl: "",
  },
  {
    id: "br004",
    name: "Veg Biryani",
    description: "Fragrant rice with seasonal vegetables and whole spices",
    price: 80,
    category: "biryani",
    isVeg: true,
    available: true,
    emoji: "🥕",
    imageUrl: "",
  },

  // ─── BAKERY ───────────────────────────────────────────────────────────────
  {
    id: "bk001",
    name: "Bread Butter",
    description: "Toasted bread slices with butter",
    price: 20,
    category: "bakery",
    isVeg: true,
    available: true,
    emoji: "🍞",
    imageUrl: "",
  },
  {
    id: "bk002",
    name: "Jam Toast",
    description: "Toasted bread with strawberry or mixed-fruit jam",
    price: 25,
    category: "bakery",
    isVeg: true,
    available: true,
    emoji: "🍞",
    imageUrl: "",
  },
  {
    id: "bk003",
    name: "Veg Puff",
    description: "Flaky pastry filled with spiced vegetable mix",
    price: 25,
    category: "bakery",
    isVeg: true,
    available: true,
    emoji: "🥐",
    imageUrl: "",
  },
  {
    id: "bk004",
    name: "Egg Puff",
    description: "Flaky pastry with a whole boiled egg and masala",
    price: 30,
    category: "bakery",
    isVeg: false,
    available: true,
    emoji: "🥐",
    imageUrl: "",
  },
  {
    id: "bk005",
    name: "Chicken Puff",
    description: "Buttery pastry filled with spiced minced chicken",
    price: 35,
    category: "bakery",
    isVeg: false,
    available: true,
    emoji: "🥐",
    imageUrl: "",
  },
  {
    id: "bk006",
    name: "Cake Slice",
    description: "Fresh-baked moist cake slice – flavour of the day",
    price: 40,
    category: "bakery",
    isVeg: true,
    available: true,
    emoji: "🎂",
    imageUrl: "",
  },

  // ─── BEVERAGES ────────────────────────────────────────────────────────────
  {
    id: "bv001",
    name: "Tea",
    description: "Hot masala chai with milk and ginger",
    price: 10,
    category: "beverages",
    isVeg: true,
    available: true,
    emoji: "☕",
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "bv002",
    name: "Coffee",
    description: "Hot filter coffee with frothed milk",
    price: 15,
    category: "beverages",
    isVeg: true,
    available: true,
    emoji: "☕",
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "bv003",
    name: "Cold Coffee",
    description: "Chilled blended coffee with milk and sugar",
    price: 40,
    category: "beverages",
    isVeg: true,
    available: true,
    emoji: "🥤",
    imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "bv004",
    name: "Lassi",
    description: "Chilled sweet or salted yoghurt drink",
    price: 30,
    category: "beverages",
    isVeg: true,
    available: true,
    emoji: "🥛",
    imageUrl: "",
  },
  {
    id: "bv005",
    name: "Buttermilk",
    description: "Chilled spiced curd drink with curry leaves",
    price: 20,
    category: "beverages",
    isVeg: true,
    available: true,
    emoji: "🥛",
    imageUrl: "",
  },
  {
    id: "bv006",
    name: "Badam Milk",
    description: "Warm saffron and almond-flavoured milk",
    price: 35,
    category: "beverages",
    isVeg: true,
    available: false,
    emoji: "🥛",
    imageUrl: "",
  },

  // ─── FRESH JUICE ──────────────────────────────────────────────────────────
  {
    id: "j001",
    name: "Orange Juice",
    description: "Freshly squeezed orange juice",
    price: 40,
    category: "fresh-juice",
    isVeg: true,
    available: true,
    emoji: "🍊",
    imageUrl: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "j002",
    name: "Watermelon Juice",
    description: "Fresh chilled watermelon juice",
    price: 35,
    category: "fresh-juice",
    isVeg: true,
    available: true,
    emoji: "🍉",
    imageUrl: "https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "j003",
    name: "Pineapple Juice",
    description: "Sweet and tangy fresh pineapple juice",
    price: 45,
    category: "fresh-juice",
    isVeg: true,
    available: true,
    emoji: "🍍",
    imageUrl: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "j004",
    name: "Grape Juice",
    description: "Fresh purple grape juice",
    price: 45,
    category: "fresh-juice",
    isVeg: true,
    available: false,
    emoji: "🍇",
    imageUrl: "",
  },
  {
    id: "j005",
    name: "Mixed Fruit Juice",
    description: "Seasonal mixed fruit blend",
    price: 50,
    category: "fresh-juice",
    isVeg: true,
    available: true,
    emoji: "🍹",
    imageUrl: "",
  },

  // ─── SANDWICH & ROLLS ─────────────────────────────────────────────────────
  {
    id: "sw001",
    name: "Veg Sandwich",
    description: "Toasted sandwich with cucumber, tomato and chutney",
    price: 35,
    category: "sandwich",
    isVeg: true,
    available: true,
    emoji: "🥪",
    imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sw002",
    name: "Cheese Sandwich",
    description: "Toasted sandwich with melted cheese and vegetables",
    price: 45,
    category: "sandwich",
    isVeg: true,
    available: true,
    emoji: "🥪",
    imageUrl: "",
  },
  {
    id: "sw003",
    name: "Chicken Sandwich",
    description: "Grilled chicken with lettuce and mayo in toasted bread",
    price: 60,
    category: "sandwich",
    isVeg: false,
    available: true,
    emoji: "🥪",
    imageUrl: "",
  },
  {
    id: "sw004",
    name: "Veg Frankie",
    description: "Spiced vegetable roll wrapped in roomali roti",
    price: 45,
    category: "sandwich",
    isVeg: true,
    available: true,
    emoji: "🌯",
    imageUrl: "",
  },
  {
    id: "sw005",
    name: "Egg Frankie",
    description: "Egg bhurji roll with onion and chutney",
    price: 55,
    category: "sandwich",
    isVeg: false,
    available: true,
    emoji: "🌯",
    imageUrl: "",
  },
  {
    id: "sw006",
    name: "Chicken Frankie",
    description: "Spiced chicken roll with mint chutney",
    price: 70,
    category: "sandwich",
    isVeg: false,
    available: true,
    emoji: "🌯",
    imageUrl: "",
  },

  // ─── PAV BHAJI ────────────────────────────────────────────────────────────
  {
    id: "pb001",
    name: "Pav Bhaji",
    description: "Spiced mashed vegetable curry with buttered pav",
    price: 60,
    category: "pav-bhaji",
    isVeg: true,
    available: true,
    emoji: "🍞",
    imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "pb002",
    name: "Cheese Pav Bhaji",
    description: "Pav bhaji topped with extra cheese and butter",
    price: 80,
    category: "pav-bhaji",
    isVeg: true,
    available: true,
    emoji: "🧀",
    imageUrl: "",
  },
  {
    id: "pb003",
    name: "Masala Pav",
    description: "Buttered pav tossed in spiced masala mixture",
    price: 40,
    category: "pav-bhaji",
    isVeg: true,
    available: true,
    emoji: "🍞",
    imageUrl: "",
  },

  // ─── ICE CREAM ────────────────────────────────────────────────────────────
  {
    id: "ic001",
    name: "Vanilla Ice Cream",
    description: "Classic vanilla scoop",
    price: 30,
    category: "ice-cream",
    isVeg: true,
    available: true,
    emoji: "🍦",
    imageUrl: "",
  },
  {
    id: "ic002",
    name: "Chocolate Ice Cream",
    description: "Rich chocolate scoop",
    price: 35,
    category: "ice-cream",
    isVeg: true,
    available: true,
    emoji: "🍫",
    imageUrl: "",
  },
  {
    id: "ic003",
    name: "Butterscotch Ice Cream",
    description: "Creamy butterscotch with caramel bits",
    price: 35,
    category: "ice-cream",
    isVeg: true,
    available: true,
    emoji: "🍬",
    imageUrl: "",
  },

  // ─── WATER ────────────────────────────────────────────────────────────────
  {
    id: "w001",
    name: "Water Bottle (500ml)",
    description: "Chilled packaged drinking water",
    price: 15,
    category: "water",
    isVeg: true,
    available: true,
    emoji: "💧",
    imageUrl: "https://images.unsplash.com/photo-1548839140-29a749e1cf4e?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "w002",
    name: "Water Bottle (1L)",
    description: "Packaged drinking water 1 litre",
    price: 20,
    category: "water",
    isVeg: true,
    available: true,
    emoji: "💧",
    imageUrl: "https://images.unsplash.com/photo-1548839140-29a749e1cf4e?w=600&auto=format&fit=crop&q=80",
  },

  // ─── ADDED ITEMS ──────────────────────────────────────────────────────────
  {
    id: "ai001",
    name: "Extra Chutney",
    description: "Coconut chutney or tomato chutney",
    price: 5,
    category: "added",
    isVeg: true,
    available: true,
    emoji: "🥣",
    imageUrl: "",
  },
  {
    id: "ai002",
    name: "Extra Sambar",
    description: "Additional bowl of sambar",
    price: 10,
    category: "added",
    isVeg: true,
    available: true,
    emoji: "🥣",
    imageUrl: "",
  },
  {
    id: "ai003",
    name: "Extra Ghee",
    description: "Pure ghee serving",
    price: 10,
    category: "added",
    isVeg: true,
    available: true,
    emoji: "🧈",
    imageUrl: "",
  },
  {
    id: "ai004",
    name: "Papad",
    description: "Crispy fried or roasted papad",
    price: 10,
    category: "added",
    isVeg: true,
    available: true,
    emoji: "🥨",
    imageUrl: "",
  },
];

/** Featured items for the home page preview (IDs only) */
const FEATURED_ITEMS = [
  "m001",   // Veg Meals
  "br001",  // Chicken Biryani
  "d002",   // Masala Dosa
  "bv002",  // Coffee
  "br004",  // Veg Biryani
  "sw004",  // Veg Frankie
  "c001",   // Veg Fried Rice
  "pb001",  // Pav Bhaji
];

/**
 * Get items by category id. Pass "all" for all items.
 * @param {string} categoryId
 * @param {"all"|"veg"|"non-veg"} vegFilter
 * @returns {MenuItem[]}
 */
function getMenuItems(categoryId = "all", vegFilter = "all") {
  let items = categoryId === "all"
    ? MENU_ITEMS
    : MENU_ITEMS.filter(i => i.category === categoryId);

  if (vegFilter === "veg")     items = items.filter(i => i.isVeg === true);
  if (vegFilter === "non-veg") items = items.filter(i => i.isVeg === false);
  return items;
}

/**
 * Search items by name (case-insensitive).
 * @param {string} query
 * @returns {MenuItem[]}
 */
function searchMenuItems(query) {
  const q = query.toLowerCase().trim();
  return MENU_ITEMS.filter(i => i.name.toLowerCase().includes(q));
}

/**
 * Get a single item by id.
 * @param {string} id
 * @returns {MenuItem|undefined}
 */
function getMenuItemById(id) {
  return MENU_ITEMS.find(i => i.id === id);
}
